
services:
  backend:
    build:
      context: .
      dockerfile: DockerFile.backend
    container_name: backend
    env_file:
      - .env
    ports:
      - "8090:8090"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ${NOTEBOOKS_HOST_DIR:-./backend/notebooks}:/app/notebooks:rw
    depends_on:
      - ollama
    
    # command: uvicorn api_service:app --host 0.0.0.0 --port 8090 --reload

  frontend:
    build:
      context: .
      dockerfile: DockerFile.frontend
    container_name: frontend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE=http://localhost:8090
      - API_BASE_INTERNAL=http://backend:8090
    depends_on:
      - backend

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    env_file:
      - .env
    volumes:
      - ollama:/root/.ollama
      - ./ollama-init.sh:/ollama-init.sh:ro
    entrypoint: ["/bin/sh", "/ollama-init.sh"]
    ports:
      - "11434:11434"
    restart: unless-stopped



volumes:
  ollama:

networks:
  default:
    name: appnet
